output: Lakshminarayanan_main.o Lakshminarayanan_subash_assn5.o
	g++ Lakshminarayanan_main.o Lakshminarayanan_subash_assn5.o -o main

Lakshminarayanan_main.o: Lakshminarayanan_main.cpp
	g++ -c Lakshminarayanan_main.cpp

Lakshminarayanan_subash_assn5.o: Lakshminarayanan_subash_assn5.cpp Lakshminarayanan_list.h
	g++ -c Lakshminarayanan_subash_assn5.cpp
